use_frameworks!

platform :ios, '9.0'

target 'UNIPPlusPods_Example' do
  pod 'UNIPPlusPods', :path => '../'
  pod 'Core', :path => '../'
  pod 'Theme', :path => '../'

  target 'UNIPPlusPods_Tests' do
    inherit! :search_paths

    
  end
end
