# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/franknet/unipplus-ios-pods.git'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Core', '~> 0.1.0' 
  pod 'Components', '~> 0.1.0'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end
